### ISSUE TITLE
Getting strange result on example data

### ISSUE THREAD

**Issue by sergak0** [neu-vi/PlanarRecon#1]
Hi, thanks for a great job! I am trying to get planars from an example data, that provided in [step 2](https://github.com/zju3dv/NeuralRecon/blob/master/DEMO.md) of your guide. I have run code in google colab and you can find my notebook [here](https://colab.research.google.com/drive/1fiNmC3FiEiasBo9jReBO1sKW3uJYxMnm?usp=sharing). Code has run wihtout issues, but the result seems to be strange (see photo). Is it a normal result or I am doing something wrong?

![image](https://user-images.githubusercontent.com/44319901/174474324-8996919f-f69b-47f6-8566-c4a05359c00d.png)

**Comment by ymingxie** [comment]
Thanks for your interest in our work! To make this part clear, I add a new file "DEMO.md", which is modified from NeuralRecon/DEMO.md. Please follow the instructions in this file. Thanks.

**Comment by sergak0** [comment]
Thank you, I will try it and reply if something went wrong
