### ISSUE TITLE
3D plane segmentation evaluation

### ISSUE THREAD

**Issue by jcliu0428** [neu-vi/PlanarRecon#18]
Hi there,

Thank you for releasing the code of this great work! I'm trying to run the evaluation scripts to reproduce the paper's results. However, it seems that the part of 3D plane segmentation (VOI, RI, SC) is somehow missing. Could you please provide the code for this part?

Many thanks and look forward to your reply!

**Comment by ymingxie** [comment]
Sure, I will upload the script for the segmentation evaluation this weekend.

**Comment by ymingxie** [comment]
Thank you again for your interest in our work. I uploaded the scripts for the segmentation eval. Please refer to https://github.com/neu-vi/PlanarRecon#evaluation-on-scannet-val-set 

Feel free to leave your questions if you meet any problem

Thanks

**Comment by jcliu0428** [comment]
Thanks Yiming!
