### ISSUE TITLE
PointTensor has been deprecated form TorchSparse

### ISSUE THREAD

**Issue by R132** [neu-vi/PlanarRecon#20]
PointTensor has been deprecated from torchsparse according to 
https://github.com/mit-han-lab/torchsparse/issues/213

could we get the compatible version of torchsparse or is there anyway to use SparseTensor replace PointTensor?

**Comment by ymingxie** [comment]
Thank you for your interest in our work! That's the version we used: https://github.com/mit-han-lab/torchsparse/tree/a41fe4b1f53f9ba27299a98162b679f9d6f449fe
