### ISSUE TITLE
How the AR demo video generated

### ISSUE THREAD

**Issue by longcw** [neu-vi/PlanarRecon#22]
Thank you for the great work! I have a very beginner's question: How did you create the AR demo video on the project page? Was it a recording from a real-time AR demo running on something like an iPad, or was it created through post-processing offline?

**Comment by ymingxie** [comment]
Hi, the AR demo was created offline. First, we record the videos and get corresponding camera poses via [ARKit](https://github.com/neu-vi/PlanarRecon/blob/main/DEMO.md). Then we run PlanarRecon to get the reconstruction results. We use [Blender](https://www.blender.org/) to render the incremental reconstruction process and add AR effects.

Thanks,
Yiming

**Comment by longcw** [comment]
@ymingxie Thanks a lot!
