### ISSUE TITLE
Not so satisfied with the result of my own dataset. Display code request for debugging.

### ISSUE THREAD

**Issue by ChiyuanFeng** [neu-vi/PlanarRecon#3]
Hello Yiming,

Thanks again for sharing this wonderful work! While I was testing on my own data. The result came out to be not so satisfying. Is it possible that you can share the display code for incremental reconstruction? So I can try the locate my problem. If not, any help for me to start with will be much appreciatted.

**Comment by ymingxie** [comment]
I didn't write the code for online visualization. I refer you to https://github.com/zju3dv/NeuralRecon/blob/master/utils.py#L246

If you'd like to save incremental reconstruction mesh, you need to call this function
https://github.com/neu-vi/PlanarRecon/blob/main/utils.py#L434 in each iteration.

**Comment by ChiyuanFeng** [comment]
> Reference in new



> I didn't write the code for online visualization. I refer you to https://github.com/zju3dv/NeuralRecon/blob/master/utils.py#L246
> 
> If you'd like to save incremental reconstruction mesh, you need to call this function https://github.com/neu-vi/PlanarRecon/blob/main/utils.py#L434 in each iteration.

Thanks a lot!

**Comment by Xuduoteng** [comment]
@ChiyuanFeng Hi, I am a student from China. I am also using planarrecon to test my data recently, can I add your WeChat to have a discuss? Best of luck with your research！
